Aad 276 create push notification function app
SkillsFundingAgency/das-push-notifications pull request #2
Opened 2024-05-09 16:34 UTC by CathyGroom

Merge required with main.

2024-05-15 11:29 UTC, abroodie requested changes
Add new SFA.DAS.PushNotifications.Application class library and then move the class SFA.DAS.PushNotifications.Functions\Services\PushNotificationsService.cs into that new project

Move classes in SFA.DAS.PushNotifications.Data.Entities namespace to SFA.DAS.PushNotifications.Model project

2024-05-15 11:29 UTC, abroodie commented on src/SFA.DAS.PushNotifications.Functions/SFA.DAS.PushNotifications.Data/Repositories/ApplicationClientRepository.cs
> +        var appClient = _context.ApplicationClients.Where(x => x.Endpoint == applicationClient.Endpoint).FirstOrDefault();
The Where filter clause can be moved to the filter in the FirstOrDefault() statement

2024-05-15 11:29 UTC, abroodie commented on src/SFA.DAS.PushNotifications.Functions/SFA.DAS.PushNotifications.Data/Repositories/ApplicationClientRepository.cs
> +        var appClient = _context.ApplicationClients.Where(x => x.Endpoint == applicationClient.Endpoint).FirstOrDefault();
The Where filter clause can be moved to the filter in the FirstOrDefault() statement

2024-05-15 11:29 UTC, abroodie commented on src/SFA.DAS.PushNotifications.Functions/SFA.DAS.PushNotifications.Data/Repositories/ApplicationClientRepository.cs
> +        if (appClient != null)
invert if to reduce indentation

2024-05-31 15:20 UTC, HussainsGitHub submitted a review, later dismissed

2024-06-01 10:40 UTC, alireid reviewed
Cursory first glance this looks brilliant

2024-06-04 16:10 UTC, alireid submitted a review, later dismissed

2024-06-12 13:35 UTC, abroodie approved these changes

2024-06-12 15:12 UTC, HussainsGitHub approved these changes

2024-06-12 15:24 UTC, merged